Repository UMC-HKT-Team-R/FE, pull requests merged in 2025-01, with the labels that each got.

#6 [Feature/1] 추천 페이지 UI 구현
  src/assets/roll-back.svg
  src/pages/recommend.tsx
  tailwind.config.js
Labels: ✨Feature

#11 [Feature/4] 기록하기 페이지 퍼블리싱
  package.json
  src/App.tsx
  src/components/.gitkeep
  src/components/calendar/index.tsx
  src/components/calendar/style.css
  src/components/layout/index.tsx
  src/constants/food-type.ts
  src/hooks/use-outside-click.ts
  src/pages/add-menu.tsx
  src/utils/.gitkeep
  src/utils/date.ts
  yarn.lock
Labels: ✨Feature

#13 [Feature/8] 마이페이지 구현
  package.json
  src/assets/profile.png
  src/pages/mypage.tsx
  tailwind.config.js
  yarn.lock
Labels: ✨Feature

#15 [Feat/12] 기록 페이지 퍼블리싱
  .github/ISSUE_TEMPLATE/feature-request.md
  .prettierrc.json
  README.md
  package.json
  src/App.tsx
  src/assets/food.png
  src/assets/trash.svg
  src/components/BlackRankingList.tsx
  src/components/InfoGrid.tsx
  src/components/WhiteRankingList.tsx
  src/components/calendar/index.tsx
  src/components/calendar/inline-calendar/index.tsx
  src/components/calendar/inline-calendar/style.css
  src/components/calendar/popup-calendar/index.tsx
  src/components/calendar/popup-calendar/style.css
  src/components/calendar/style.css
  src/components/card/index.tsx
  src/components/layout/footer.tsx
  src/components/layout/header.tsx
  src/constants/food-type.ts
  src/contexts/AuthContext.tsx
  src/pages/add-menu.tsx
  src/pages/history.tsx
  src/pages/home.tsx
  src/pages/login.tsx
  src/pages/mypage.tsx
  src/pages/post.tsx
  src/pages/recommend.tsx
  yarn.lock
Labels: ✨Feature

#18 [Fix/17] UI 수정 사항 반영
  eslint.config.js
  src/pages/history.tsx
  src/pages/home.tsx
Labels: ✨Feature

#23 [Feature/8] 카카오 로그인 api 연결
  .gitignore
  src/App.tsx
  src/pages/callback.tsx
  src/pages/login.tsx
  src/services/get-login.ts
Labels: ✨Feature

#27 [Fix/20] 배포 후 오류 해결
  package.json
  src/assets/add.svg
  src/assets/roll-back.svg
  src/assets/trash.svg
  src/components/InfoGrid.tsx
  src/components/PostDetail.tsx
  src/components/PostWrite.tsx
  src/components/calendar/inline-calendar/style.css
  src/components/layout/footer.tsx
  src/components/layout/header.tsx
  src/index.css
  src/pages/history.tsx
  src/pages/home.tsx
  src/pages/mypage.tsx
  src/pages/post.tsx
  src/pages/recommend.tsx
  tailwind.config.js
Labels: ✨Feature

#32 [remove] 파일 구조 변경
  src/pages/callback.tsx
  src/services/member.ts
Labels: 🐞Fix

#33 Feature/14 추천 글 페이지 구현
  src/assets/Rectangle 4.svg
  src/assets/Rectangle 5.svg
  src/assets/Rectangle 6.svg
  src/assets/Rectangle 7.svg
  src/components/BlackRankingList.tsx
  src/components/InfoGrid.tsx
  src/components/PostDetail.tsx
  src/components/SecretDetail.tsx
  src/components/WhiteRankingList.tsx
  src/pages/home.tsx
Labels: ✨Feature

#38 [Feature/34] refreshToken api 연결
  src/components/PostDetail.tsx
  src/pages/home.tsx
  src/services/api.ts
Labels: ✨Feature, 📫API

#40 Fix/35 홈화면, 추천글 디테일 수정
  src/components/InfoGrid.tsx
  src/components/SecretDetail.tsx
  src/pages/home.tsx
Labels: ✨Feature

#39 [Feat/28] 기록 추가 API 연동
  src/assets/food.png
  src/components/PostDetail.tsx
  src/components/PostWrite.tsx
  src/components/calendar/inline-calendar/index.tsx
  src/components/card/index.tsx
  src/components/layout/index.tsx
  src/constants/food-type.ts
  src/pages/add-menu.tsx
  src/pages/history.tsx
  src/pages/recommend.tsx
  src/services/calendar.ts
  src/services/post.ts
  src/services/recommend.ts
  src/utils/date.ts
Labels: ✨Feature

#45 [Feat/43] 캘린더 API 연동
  index.html
  public/favicon.svg
  src/components/calendar/inline-calendar/index.tsx
  src/components/card/index.tsx
  src/pages/history.tsx
  src/pages/home.tsx
  src/pages/mypage.tsx
  src/services/calendar.ts
  src/services/my.ts
Labels: ✨Feature
